#!/sbin/busybox sh
export PATH="/res/customconfig/actions/push-actions:${PATH}";

(
echo "/dev/block/vold/public:179_11" > /sys/devices/virtual/android_usb/android0/f_mass_storage/lun0/file;

if [ -e /dev/block/vold/public:179_13 ]; then
	echo "/dev/block/vold/public:179_13" > /sys/devices/virtual/android_usb/android0/f_mass_storage/lun1/file;
fi;
)&

echo "Try now to open usb drive/s.";
